In [33]:
import pandas as pd
import numpy as np

df = pd.read_csv('marketing_campaign_data_messy.csv')
print(f"Loaded Dataset: {df.shape[0]} rows, {df.shape[1]} columns")

Loaded Dataset: 2020 rows, 12 columns

In [34]:
df

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31 00:00:00,2023-11-13,TikTok,30592,586,$503.95,77.0,1,NaN,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01 00:00:00,2023-09-26,Google Ads,20097,897,1641.0,162.0,0,NaN,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09 00:00:00,2023-02-21,Instagram,33254,1117,883.82,214.0,0,NaN,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30 00:00:00,2023-04-27,Facebook,68728,2960,4198.5,591.0,Yes,NaN,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26 00:00:00,2023-07-09,Email,96402,1090,1315.59,66.0,Y,NaN,EM

In [35]:
print(df.columns.tolist())

[' Campaign_ID ', 'Campaign_Name', 'Start_Date', 'End_Date', 'Channel', 'Impressions', 'Clicks ', 'Spend', 'Conversions', 'Active', 'Clicks', 'Campaign_Tag']

In [36]:
# HEADER CLEANER

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
print(df.columns.tolist())

['campaign_id', 'campaign_name', 'start_date', 'end_date', 'channel', 'impressions', 'clicks', 'spend', 'conversions', 'active', 'clicks', 'campaign_tag']

In [37]:
# TYPE CONVERSION & CURRENCY CLEANING

clean_spend = df['spend'].astype(str).str.contains('$')
print(df.loc[clean_spend, ['campaign_id', 'spend']].head(5))

df['spend'] = df['spend'].astype(str).str.replace(r'[^\d.-]', '', regex=True)
df['spend'] = pd.to_numeric(df['spend'])

print('FIX APPLIED')
print(df.loc[clean_spend, ['campaign_id', 'spend']].head(5))

  campaign_id    spend
0   CMP-00001  $102.82
1   CMP-00002    24.33
2   CMP-00003  1323.39
3   CMP-00004  2180.38
4   CMP-00005   252.44
FIX APPLIED
  campaign_id    spend
0   CMP-00001   102.82
1   CMP-00002    24.33
2   CMP-00003  1323.39
3   CMP-00004  2180.38
4   CMP-00005   252.44

In [38]:
# CATEGORICAL TYPOS

print(df['channel'].unique())

cleanupMap =  {
    'Facebok' : 'Facebook',
    'Insta_gram' : 'Instagram',
    'Tik_Tok' : 'TikTok',
    'Gogle' : 'Google Ads',
    'E-mail' : 'Email',
    'N/A' : np.nan
}
df['channel'] = df['channel'].replace(cleanupMap)
print('FIX APPLIED')
print(df['channel'].unique())

<StringArray>
[    'TikTok',   'Facebook',      'Email',  'Instagram', 'Google Ads',
     'E-mail',          nan,      'Gogle',    'Tik_Tok',    'Facebok',
 'Insta_gram']
Length: 11, dtype: str
FIX APPLIED
<StringArray>
['TikTok', 'Facebook', 'Email', 'Instagram', 'Google Ads', nan]
Length: 6, dtype: str

In [39]:
# HANDLING MISSING VALUES

print(df['active'].unique())

boolMap = {
    'Yes' : True,
    'No' : False,
    'Y' : True,
    '0' : False,
    '1' : True,
    1 : True,
    0 : False
}
df['active'] = df['active'].map(boolMap).fillna(False).astype(bool)
print('FIX APPLIED')
print(df['active'].unique())

<StringArray>
['Y', '0', 'No', 'True', 'Yes', '1', 'False']
Length: 7, dtype: str
FIX APPLIED
[ True False]

In [40]:
# DATE PARSING

print(df['start_date'].dtypes)

df['start_date'] = pd.to_datetime(df['start_date'], errors='coerce')
df['end_date'] = pd.to_datetime(df['end_date'], dayfirst=True, errors='coerce')

print('FIX APPLIED')
print(df['start_date'].dtypes)

str
FIX APPLIED
datetime64[us]

/var/folders/fm/yysrpk0n5p3_hn67jdk6hggm0000gn/T/ipykernel_1166/3510332366.py:6: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['end_date'] = pd.to_datetime(df['end_date'], dayfirst=True, errors='coerce')

In [41]:
df = df.loc[:, ~df.columns.duplicated()]

In [42]:
df

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,True,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,False,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,False,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,False,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,True,FA
...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,TikTok,30592,586,503.95,77.0,True,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,Google Ads,20097,897,1641.00,162.0,False,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,Instagram,33254,1117,883.82,214.0,False,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,Facebook,68728,2960,4198.50,591.0,True,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,Email,96402,1090,1315.59,66.0,True,EM

In [43]:
# LOGICAL INTEGRITY CHECKS (CLICKS SHOULD NOT EXCEED IMPRESSIONS)

invalid_clicks = df['clicks'] > df['impressions']
print(df.loc[invalid_clicks, ['campaign_id', 'clicks', 'impressions']].head(5))

Empty DataFrame
Columns: [campaign_id, clicks, impressions]
Index: []

In [45]:
# LOGICAL INTEGRITY CHECKS (TIME TRAVEL)

invalid_dates = df['end_date'] < df['start_date']
print(df.loc[invalid_dates, ['campaign_id', 'start_date', 'end_date']].head(5))

df.loc[invalid_dates, 'end_date'] = df.loc[invalid_dates, 'start_date'] + pd.Timedelta(days=30)
print('FIX APPLIED')
print(df.loc[invalid_dates, ['campaign_id', 'start_date', 'end_date']].head(5))

    campaign_id start_date   end_date
23    CMP-00024 2023-05-06 2023-05-01
54    CMP-00055 2023-09-01 2023-08-27
71    CMP-00072 2023-02-01 2023-01-27
156   CMP-00157 2023-12-06 2023-12-01
200   CMP-00201 2023-01-11 2023-01-06
FIX APPLIED
    campaign_id start_date   end_date
23    CMP-00024 2023-05-06 2023-06-05
54    CMP-00055 2023-09-01 2023-10-01
71    CMP-00072 2023-02-01 2023-03-03
156   CMP-00157 2023-12-06 2024-01-05
200   CMP-00201 2023-01-11 2023-02-10

In [47]:
# HANDLING OUTLIERS

Q1 = df['spend'].quantile(0.25)
Q3 = df['spend'].quantile(0.75)

IQR = Q3 - Q1
upperLimit = Q3 + (3 * IQR)

outlierMask = df['spend'] > upperLimit
print(df.loc[outlierMask, ['campaign_id', 'spend']].head(5))

print('FIX APPLIED')
df.loc[outlierMask, 'spend'] = upperLimit
print(df.loc[outlierMask, ['campaign_id', 'spend']].head(5))

     campaign_id      spend
789    CMP-00790  500000.00
1443   CMP-01444    8921.51
1460   CMP-01461  500000.00
1718   CMP-01719  500000.00
1754   CMP-01755  500000.00
FIX APPLIED
     campaign_id      spend
789    CMP-00790  8603.5375
1443   CMP-01444  8603.5375
1460   CMP-01461  8603.5375
1718   CMP-01719  8603.5375
1754   CMP-01755  8603.5375

In [50]:
# STRING PARSING (EXTRACTING DEVICE FROM CAMPAIGN NAME)

print(df['campaign_name'].head(5))

df['season'] = df['campaign_name'].str.extract(r'Q\d_([^_]+)')
print('EXTRACTED SEASON')
print(df[['campaign_name', 'season']].head(5))

0         Q4_Summer_CMP-00001
1         Q1_Launch_CMP-00002
2         Q3_Winter_CMP-00003
3    Q1_BlackFriday_CMP-00004
4         Q2_Winter_CMP-00005
Name: campaign_name, dtype: str
EXTRACTED SEASON
              campaign_name       season
0       Q4_Summer_CMP-00001       Summer
1       Q1_Launch_CMP-00002       Launch
2       Q3_Winter_CMP-00003       Winter
3  Q1_BlackFriday_CMP-00004  BlackFriday
4       Q2_Winter_CMP-00005       Winter

In [55]:
col = df.pop('season')
df.insert(2, 'season', col)

In [56]:
df

,campaign_id,campaign_name,season,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,Summer,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,True,TI
1,CMP-00002,Q1_Launch_CMP-00002,Launch,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,False,FA
2,CMP-00003,Q3_Winter_CMP-00003,Winter,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,False,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,BlackFriday,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,False,TI
4,CMP-00005,Q2_Winter_CMP-00005,Winter,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,True,FA
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,Summer,2023-10-31,2023-11-13,TikTok,30592,586,503.95,77.0,True,TI
2016,CMP-01255,Q4_Summer_CMP-01255,Summer,2023-09-01,2023-09-26,Google Ads,20097,897,1641.00,162.0,False,GO
2017,CMP-01050,Q2_Launch_CMP-01050,Launch,2023-02-09,2023-02-21,Instagram,33254,1117,883.82,214.0,False,IN
2018,CMP-01118,Q4_Winter_CMP-01118,Winter,2023-03-30,2023-04-27,Facebook,68728,2960,4198.50,591.0,True,FA
2019,CMP-01554,Q4_Launch_CMP-01554,Launch,2023-06-26,2023-07-09,Email,96402,1090,1315.59,66.0,True,EM